baseURL = "https://example.com"
title = "HUGO.386"
languageCode = "en"
DefaultContentLanguage = "en"
theme = "hugo.386"
preserveTaxonomyNames = true

[params]
    # The name to display as main title in the home page
    mainpagetitle = "HUGO.386"

    # The subtitle to display under the title in the home page
    mainpagesubtitle = "Welcome to the early 90s!" 

    # The name to display as main title in the home page
    mainpagedesc = "This theme is the Hugo port of the BOOTSTRA.386 theme for a cool retro look on your blog. Check the links below to access the posts."

    # The name to display in the copyright section in the footer
    copyrightname = "JM Fergeau"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    copyrighturl = "http://jmf-portfolio.netlify.com"

    # Show the "built on Hugo" disclaimer
    showhugo = true

    # Urls for social networks
    facebook = "https://facebook.com"
    twitter = "https://twitter.com"
    linkedin = "https://linkedin.com"
    github = "https://github.com"
    gitlab = "https://gitlab.com"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

  [[menu.main]]
    identifier = "posts"
    name = "All posts"
    url = "/post/"
    weight = 20

[taxonomies]
category = "categories"
tag = "tags"


[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true